# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-01 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=1, max_length=1),
        ),
    ]
